"""Add Order Table

Revision ID: d396f4e3853b
Revises: 3c7c056a2ee3
Create Date: 2024-03-06 10:25:56.518674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd396f4e3853b'
down_revision: Union[str, None] = '3c7c056a2ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('article', sa.String(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.String(), nullable=True),
                    sa.Column('total', sa.String(), nullable=True),
                    sa.Column('earnings', sa.String(), nullable=True),
                    sa.Column('order_date', sa.TIMESTAMP(), nullable=False),
                    sa.Column('arrive_date', sa.TIMESTAMP(), nullable=True)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
