"""update table

Revision ID: 3c7c056a2ee3
Revises: e5690d68c2c3
Create Date: 2024-02-18 12:12:55.490287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7c056a2ee3'
down_revision: Union[str, None] = 'e5690d68c2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('article')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    # ### end Alembic commands ###
